# 创建Array
有5种方式创建Array：
1. 从Python的list、tuple等类型中转换
2. 使用内建函数（arange、ones、zeros等）创建
3. 从硬盘中读取数据。
4. 从二进制流的string或buffer中创建
5. 使用特殊的函数建立（如random等）

In [1]:
import numpy as np

## 1. 从list或tuple中转换

In [2]:
x = np.array([1, 2, 3,])
# 类型自动转换
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

## 2. 内建函数创建
* `np.zeros(数组的纬度tuple)`: 全部为0
* `np.arange(开始值, 终止值, 要创建的个数n)`: 创建均匀递增的n个数组成的array，生成的array包含开始值和终止值。
* `np.eye(n)`: 创建大小是n的单位矩阵

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
a.dtype

dtype('float64')

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
np.linspace(1, 2, 11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [9]:
np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [10]:
np.indices((2, 2))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [11]:
np.indices((2, 3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

## 3. 从硬盘中读取Array

## 4. 从二进制流的string或buffer中创建

In [12]:
import numpy as np
from io import StringIO

In [13]:
data = u"1, 2, 3\n4, 5, 6"
np.genfromtxt(StringIO(data), delimiter=",")

array([[1., 2., 3.],
       [4., 5., 6.]])

comments参数：跳过注释所在行，默认是`#`。
numpy1.7后，当comments=None时，不启用忽略注释的功能

In [14]:
data = u"""#
# 注释
# 我也是注释 需要忽略掉
1, 2
3, 4
5, 6 # 这是第3行
7, 8
# 我又回来了
9, 0
"""

np.genfromtxt(StringIO(data), delimiter=",", comments="#")

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

In [15]:
np.genfromtxt(StringIO(data), delimiter=',')

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.],
       [9., 0.]])

使用usecols参数选择要初始化的列

In [16]:
# 选择第1列和最后一列传入
data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), usecols=(0, -1))

array([[1., 3.],
       [4., 6.]])

如果列有名字，也可以用名字执行要传入的列

In [17]:
data = u"1 2 3\n4 5 6"
np.genfromtxt(StringIO(data), names="a, b, c", usecols=("a", "c"))

array([(1., 3.), (4., 6.)], dtype=[('a', '<f8'), ('c', '<f8')])

使用`skip_header=n`, `skip_footer=m`忽略掉前n行和后m行数据

In [18]:
data = u"\n".join(str(i) for i in range(10))
np.genfromtxt(StringIO(data),)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
np.genfromtxt(StringIO(data), skip_header=1, skip_footer=1)

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [20]:
np.genfromtxt(StringIO(data), skip_header=3, skip_footer=5)

array([3., 4.])