In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a.dtype

dtype('int64')

In [4]:
a.dtype.name

'int64'

## 强制类型转换 Cast
### 方法1

In [5]:
a = np.arange(5)
a = a.astype(float)
print(a.dtype)
a

float64


array([0., 1., 2., 3., 4.])

In [6]:
a = np.arange(5)
a = a.astype(np.float32)
print(a.dtype)
a

float32


array([0., 1., 2., 3., 4.], dtype=float32)

### 方法2

In [7]:
a = np.arange(5)
a = np.array(a, dtype=np.float32)
print(a.dtype)
a

float32


array([0., 1., 2., 3., 4.], dtype=float32)

### 方法3

In [8]:
a = np.arange(5)
a = np.float32(a)
a

array([0., 1., 2., 3., 4.], dtype=float32)

## 错误的强制转换做法

In [9]:
# 错误的强制转换做法
a = np.arange(5)
a.dtype = np.float64
a

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [10]:
# 错误的强制转换做法
a = np.arange(5)
a.dtype = np.float64()
a

array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])