# 索引 Indexing
一些要注意到的点

当使用切片时并没有产生新的array，实际上是在原来的data上产生了一个view。如果原来的data不再使用，推荐明确的调用`copy`。

In [1]:
import numpy as np

In [2]:
# 举例
x = np.arange(10)
y = x[:5]
y[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [3]:
x = np.arange(10)
y = x[:5].copy()
y[0] = 10
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1. 选取一个元素

### 1.1 向量

In [4]:
# 向量
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[2]

2

In [6]:
x[-2]

8

### 1.2 矩阵

In [7]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
x[1, 3]

7

In [9]:
x[1, -1]

7

In [10]:
# 性能更低
x[1][3]

7

## 2. 选取一行或一列

### 2.1 矩阵

In [11]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
x[0]

array([0, 1, 2, 3])

In [13]:
x[:, 0]

array([0, 4, 8])

In [14]:
x[-1]

array([ 8,  9, 10, 11])

In [15]:
x[:, -1]

array([ 3,  7, 11])

## 3. 选取一块

### 3.1 向量

In [16]:
x = np.arange(12)
x[2: 5]

array([2, 3, 4])

In [17]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
x[1:7:2]

array([1, 3, 5])

In [19]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [20]:
y[1:5:2, ::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

## 用数组索引Array
返回的是一个原Array的copy

In [21]:
x = np.arange(10) * 10
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
x[[1, 3, 6, 7, 8]]

array([10, 30, 60, 70, 80])

In [23]:
x[[1, 2, 2, -1, -2]]

array([10, 20, 20, 90, 80])

In [24]:
x[np.array([1, 1, -1, -1,])]

array([10, 10, 90, 90])

In [25]:
# 返回的是原Array的copy
y = x[[1, 6, 9]]
y[0] = 123
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [26]:
x[np.array([[1,1],[2,3]])]

array([[10, 10],
       [20, 30]])

## 索引多维Array

In [27]:
# 用坐标(0, 0), (2, 1), (4, 2)这3个元素构建一个Array
y = np.arange(35).reshape(5,7)
print(y)
y[np.array([0,2,4]), np.array([0,1,2])]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


array([ 0, 15, 30])

In [28]:
# 利用广播机制选取(0, 1), (2, 1), (4, 1)
y[np.array([0,2,4]), 1]

array([ 1, 15, 29])

## Boolean表达式索引Array
Boolean or "mask" index arrays

In [29]:
x = np.arange(10)
x[x > 5]

array([6, 7, 8, 9])

In [30]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [31]:
b = y>25
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [32]:
b[:, 5]

array([False, False, False,  True,  True])

In [33]:
y[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [34]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [35]:
# 2 * 3
b = np.array([[True, True, False], [False, True, True]])

In [36]:
# 在选择时只看前两纬度， 将第三个纬度看作是一个元素
# 则选择（1， ：， ：）的前两行，（2， ：， ：）后两行
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## 用切片合并索引数组
Combining index arrays with slices

In [37]:
y = np.arange(35).reshape(5, 7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [38]:
y[np.array([0,2,4]), 1:3]

array([[ 1,  2],
       [15, 16],
       [29, 30]])

In [39]:
b = y > 20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [40]:
y[b[:,5], 1:3]

array([[22, 23],
       [29, 30]])

## Structural indexing tools

In [41]:
y = np.arange(35).reshape(5, 7)
print(y)
print(y.shape)
y = y[:, np.newaxis, :]
y

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
(5, 7)


array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]]])

In [42]:
y.shape

(5, 1, 7)

In [43]:
z = np.arange(81).reshape(3, 3, 3, 3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [44]:
# 以下两个表达式等价
z[1, ..., 2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

In [45]:
z[1, :, :, 2]

array([[29, 32, 35],
       [38, 41, 44],
       [47, 50, 53]])

## 赋值

In [46]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[2:8] = 1
x

array([0, 1, 1, 1, 1, 1, 1, 1, 8, 9])

In [48]:
# 使用boolean的赋值技巧
x = np.arange(0, 50, 10)
x

array([ 0, 10, 20, 30, 40])

In [49]:
x[np.array([1, 3, 4])] += 1
x

array([ 0, 11, 20, 31, 41])

**赋值前，先建立了一个临时Array，再赋值，之后再返回给原Array。所以1被赋值了3次，而不是`+=1`3次**

官方文档原文：
Where people expect that the 1st location will be incremented by 3. In fact, it will only be incremented by 1. The reason is because a new array is extracted from the original (as a temporary) containing the values at 1, 1, 3, 1, then the value 1 is added to the temporary, and then the temporary is assigned back to the original array. Thus the value of the array at x[1]+1 is assigned to x[1] three times, rather than being incremented 3 times.

In [50]:
x = np.arange(0, 50, 10)
x[np.array([1, 1, 3, 1])] += 1
x

array([ 0, 11, 20, 31, 40])

## Dealing with variable numbers of indices within programs

In [51]:
z = np.arange(81).reshape(3, 3, 3, 3)
z

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [52]:
indices = (0, 0, 0, 0)
z[indices]

0

In [53]:
indices = (2, 2, 2, 2)
z[indices]

80

In [54]:
# same as [1,1,1,0:2]
# slice是python的内建函数
indices = (1,1,1,slice(0,2))
z[indices]

array([39, 40])

In [55]:
indices = (1, Ellipsis, 1) # same as [1,...,1]
z[indices]

array([[28, 31, 34],
       [37, 40, 43],
       [46, 49, 52]])

In [56]:
z[[1,1,1,1]] # produces a large array

array([[[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]]])

In [57]:
z[(1,1,1,1)] # returns a single value

40