In [1]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [3]:
# 转置 transpose
print(a.transpose())
print()
print(a.T)

[[1. 3.]
 [2. 4.]]

[[1. 3.]
 [2. 4.]]


In [4]:
# 逆 inverse
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
# eye 代表 ”I“， "eye" represents "I"
eye = np.eye(2)
np.linalg.inv(eye)

array([[1., 0.],
       [0., 1.]])

In [6]:
j = np.array([
    [0., 1.],
    [1., 0.],
])
j

array([[0., 1.],
       [1., 0.]])

In [7]:
# 点积， matrix product
j @ j

array([[1., 0.],
       [0., 1.]])

In [8]:
j.dot(j)

array([[1., 0.],
       [0., 1.]])

In [11]:
# 叉积，
j * j

array([[0., 1.],
       [1., 0.]])

In [9]:
# 对角线元素之和
np.trace(j)

0.0

In [10]:
np.trace(eye)

2.0