# 基础语法

NumPy的主要对象是含有相同元素的多维数组。
在Numpy中纬度被称为axes。

## 创建数组
初始化数组时，数组的大小必须是已知的。

In [1]:
import numpy as np

# initial an array
a = np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
a.dtype

dtype('int64')

In [3]:
a = np.array(
    [[1.2, 2, 3],
     [4, 5, 6],
     [7, 8, 9],]
)
a

array([[1.2, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

In [4]:
a.dtype

dtype('float64')

In [5]:
a = np.array([(1, 2), (3, 4)], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [6]:
def f(x, y):
    return 10*x + y

a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

### 特殊矩阵

In [7]:
# 单位阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# 零矩阵
z = np.zeros((3, 4))

In [9]:
z.dtype

dtype('float64')

In [10]:
# 全部为1的矩阵
np.ones((3, 4), dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
# 未初始化的矩阵，输出与当时内存的值相关
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 随机创建
np.random.random((4, 3))

array([[0.78107242, 0.17928388, 0.46105338],
       [0.73351382, 0.63354025, 0.26412321],
       [0.62593189, 0.12072879, 0.90923083],
       [0.76088565, 0.77404881, 0.30561779]])

### 类range初始化

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [15]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

因为float类型有精度的问题，所以每一次使用arange初始化的值可能是不同的(每一次加法都会损失精度）。推荐使用`linspace`函数解决此类问题

In [17]:
from numpy import pi
# start, end, 要生成多少个
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
# 非常适合绘图
x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)

## 查看数组的属性

In [19]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
# 纬度
a.shape

(3, 5)

In [21]:
a.shape[0]

3

In [22]:
a.shape[1]

5

In [23]:
# 有几维
a.ndim

2

In [24]:
# 所存储的数据类型
a.dtype

dtype('int64')

In [25]:
a.dtype.name

'int64'

In [26]:
# 每一个元素所占用内存大小， 单位：字节 bytes
a.itemsize

8

In [27]:
# a的元素总数量
a.size

15

In [28]:
type(a)

numpy.ndarray

## 打印数组
**在打印时，一个纬度元素数量超过1000个时，numpy会忽略中间的元素。**使用`np.set_printoptions(threshold=np.nan)`打印所有元素

In [29]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [30]:
b = np.arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
c = np.arange(24).reshape(2,3,4) 
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [32]:
# 数组太大时，numpy会自动跳过中间的元素
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [33]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [34]:
# 强制输出全部的元素
np.set_printoptions(threshold=np.nan)
print(np.arange(1001*5).reshape(5,1001))
# 恢复设置，默认值是1000个以后就跳过
np.set_printoptions(threshold=1000)

[[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
    14   15   16   17   18   19   20   21   22   23   24   25   26   27
    28   29   30   31   32   33   34   35   36   37   38   39   40   41
    42   43   44   45   46   47   48   49   50   51   52   53   54   55
    56   57   58   59   60   61   62   63   64   65   66   67   68   69
    70   71   72   73   74   75   76   77   78   79   80   81   82   83
    84   85   86   87   88   89   90   91   92   93   94   95   96   97
    98   99  100  101  102  103  104  105  106  107  108  109  110  111
   112  113  114  115  116  117  118  119  120  121  122  123  124  125
   126  127  128  129  130  131  132  133  134  135  136  137  138  139
   140  141  142  143  144  145  146  147  148  149  150  151  152  153
   154  155  156  157  158  159  160  161  162  163  164  165  166  167
   168  169  170  171  172  173  174  175  176  177  178  179  180  181
   182  183  184  185  186  187  188  189  190  191  192  193  1

## 基础操作

In [35]:
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80]])
b = np.arange(1, 9).reshape((2, 4))

print('a:\n', a)
print('b:\n', b)

a:
 [[10 20 30 40]
 [50 60 70 80]]
b:
 [[1 2 3 4]
 [5 6 7 8]]


**所有的操作都是对应元素之间的算数操作，包括乘法和除法！！！**

In [36]:
a + b

array([[11, 22, 33, 44],
       [55, 66, 77, 88]])

In [37]:
a - b

array([[ 9, 18, 27, 36],
       [45, 54, 63, 72]])

In [38]:
a * b

array([[ 10,  40,  90, 160],
       [250, 360, 490, 640]])

In [39]:
a / b

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [40]:
a + 1

array([[11, 21, 31, 41],
       [51, 61, 71, 81]])

In [41]:
a - 1

array([[ 9, 19, 29, 39],
       [49, 59, 69, 79]])

In [42]:
a * 2

array([[ 20,  40,  60,  80],
       [100, 120, 140, 160]])

In [43]:
# 自动做类型转换
a / 2

array([[ 5., 10., 15., 20.],
       [25., 30., 35., 40.]])

In [44]:
a ** 2

array([[ 100,  400,  900, 1600],
       [2500, 3600, 4900, 6400]])

In [45]:
np.sin(a)

array([[-0.54402111,  0.91294525, -0.98803162,  0.74511316],
       [-0.26237485, -0.30481062,  0.77389068, -0.99388865]])

In [46]:
a < 40

array([[ True,  True,  True, False],
       [False, False, False, False]])

### 矩阵运算

In [47]:
A = np.array([[1, 1],
              [0, 1]])

In [48]:
B = np.array([[2, 0],
              [3, 4]])

In [49]:
# 叉积
A * B

array([[2, 0],
       [0, 4]])

In [50]:
# 点积 python >= 3.5支持
A @ B

array([[5, 4],
       [3, 4]])

In [51]:
# 点积
A.dot(B)

array([[5, 4],
       [3, 4]])

类似`+=`这种形式在数字与矩阵操作时成立，但是矩阵与矩阵之间这种操作不一定成立

In [52]:
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
b = np.random.random((2,3))
b

array([[0.46030441, 0.55207034, 0.29789345],
       [0.97779075, 0.97831739, 0.07438167]])

In [54]:
# b是float类型，不能自动转换为int类型，所以不能做+=操作
try:
    a += b
except TypeError as e:
    print(e)

Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'


In [55]:
a = a + b
a

array([[1.46030441, 1.55207034, 1.29789345],
       [1.97779075, 1.97831739, 1.07438167]])

In [56]:
a = np.ones((2,3), dtype=int)
b += a
b

array([[1.46030441, 1.55207034, 1.29789345],
       [1.97779075, 1.97831739, 1.07438167]])

## 通用函数 Universal Functions
NumPy提供了常用的数学函数，如sin、cos、exp、sqrt等。在NumPy中这些被称为“universal functions”(ufunc).在内部，函数对矩阵中的每一个元素进行计算。

In [57]:
A = np.arange(3)
A

array([0, 1, 2])

In [58]:
np.exp(A)

array([1.        , 2.71828183, 7.3890561 ])

In [59]:
np.sqrt(A)

array([0.        , 1.        , 1.41421356])

In [60]:
B = np.array([2., -1., 4.])
np.add(A, B)

array([2., 0., 6.])

其他可以使用的函数：
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, inv, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

## 索引、切片、迭代  Indexing, Slicing and Iterating
对于向量，这些操作的结果和Python的可迭代类型是相同的。

### 向量

In [61]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [62]:
# 索引 Indexing
a[2]

8

In [63]:
# 切片 Slicing
print(a[2:5])
print(a[:6:2])
print(a[::-1])

[ 8 27 64]
[ 0  8 64]
[729 512 343 216 125  64  27   8   1   0]


In [64]:
# 迭代 Iterating
for i in a:
    print(i)

0
1
8
27
64
125
216
343
512
729


### 二维矩阵

In [65]:
def f(x, y):
    return 10*x + y

a = np.fromfunction(f, (5, 4), dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [66]:
# 索引 Indexing
# 取第2行，第3列，索引从0开始
a[2, 3]

23

In [67]:
# 索引一行
a[2]

array([20, 21, 22, 23])

In [68]:
# 索引一列
a[:, 2]

array([ 2, 12, 22, 32, 42])

In [69]:
# 取第0、1、2、3行中的第1个元素，索引从1开始
a[0:4, 1]

array([ 1, 11, 21, 31])

In [70]:
a[:, 1]

array([ 1, 11, 21, 31, 41])

In [71]:
a[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [72]:
# 最后一行
a[-1]

array([40, 41, 42, 43])

In [73]:
# 倒数第二行
a[-2]

array([30, 31, 32, 33])

In [74]:
# 最后一列
a[:, -1]

array([ 3, 13, 23, 33, 43])

In [75]:
# 倒数第二行
a[:, -2]

array([ 2, 12, 22, 32, 42])

### 多维矩阵

In [76]:
# 三维矩阵
a = np.array([
    [[0, 1, 2],
     [3, 4, 5]],
    
    [[0, 10, 20],
     [30, 40, 50]]
])
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 0, 10, 20],
        [30, 40, 50]]])

In [77]:
a.shape

(2, 2, 3)

In [78]:
a[0, 0, 0]

0

In [79]:
# 与 a[0, :, :]， a[0, ...]等价
a[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
a[0, :, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
a[0, ...]

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
a[..., 2]

array([[ 2,  5],
       [20, 50]])

In [83]:
a[:, :, 2]

array([[ 2,  5],
       [20, 50]])

In [84]:
# 迭代
for row in a:
    print(row)

[[0 1 2]
 [3 4 5]]
[[ 0 10 20]
 [30 40 50]]


In [85]:
for element in a.flat:
    print(element)

0
1
2
3
4
5
0
10
20
30
40
50


In [86]:
# 切片
a[0:1]

array([[[0, 1, 2],
        [3, 4, 5]]])

## Shape manipulation
`a.ravel()`, `a.reshape(6,2)`, `a.T`都会返回一个新的数组，不会修改原有的数组

In [87]:
# np.floor向下取整
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 0., 7., 2.],
       [9., 4., 8., 6.],
       [2., 8., 3., 8.]])

In [88]:
a.shape

(3, 4)

In [89]:
# 转换为向量
a.ravel()

array([7., 0., 7., 2., 9., 4., 8., 6., 2., 8., 3., 8.])

In [90]:
a

array([[7., 0., 7., 2.],
       [9., 4., 8., 6.],
       [2., 8., 3., 8.]])

In [91]:
a.reshape(6,2)

array([[7., 0.],
       [7., 2.],
       [9., 4.],
       [8., 6.],
       [2., 8.],
       [3., 8.]])

In [92]:
# 转置
a.T

array([[7., 9., 2.],
       [0., 4., 8.],
       [7., 8., 3.],
       [2., 6., 8.]])

In [93]:
# 原地改变矩阵的shape
a

array([[7., 0., 7., 2.],
       [9., 4., 8., 6.],
       [2., 8., 3., 8.]])

In [94]:
a.resize(6, 2)
a

array([[7., 0.],
       [7., 2.],
       [9., 4.],
       [8., 6.],
       [2., 8.],
       [3., 8.]])

In [95]:
# reshape可以自动判断列纬度
a.reshape(3, -1)

array([[7., 0., 7., 2.],
       [9., 4., 8., 6.],
       [2., 8., 3., 8.]])

In [96]:
# resize不能自动判断纬度
try:
    a.resize(6, -1)
except ValueError as e:
    print(e)

negative dimensions not allowed


## 合并矩阵

In [97]:
a = np.arange(0, 4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [98]:
b = np.arange(4, 8).reshape(2, 2)
b

array([[4, 5],
       [6, 7]])

In [99]:
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [100]:
np.hstack((a, b))

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

### 仅限2纬矩阵使用

In [101]:
np.column_stack((a, b))

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [102]:
np.row_stack((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

## 切分矩阵

In [103]:
a = np.arange(0, 16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [105]:
for m in np.hsplit(a, 2):
    print(m)
    print()

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]



In [106]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [107]:
for m in np.vsplit(a, 2):
    print(m)
    print()

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]



In [108]:
a = np.arange(0, 24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [109]:
np.hsplit(a,3) 

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [110]:
# 左闭右开， 切分为包含的列是0-2、 3-4、 4-11的3个矩阵
np.hsplit(a,(3,5))

[array([[ 0,  1,  2],
        [12, 13, 14]]), array([[ 3,  4],
        [15, 16]]), array([[ 5,  6,  7,  8,  9, 10, 11],
        [17, 18, 19, 20, 21, 22, 23]])]

In [111]:
for m in np.hsplit(a, (3, 5)):
    print(m)
    print()

[[ 0  1  2]
 [12 13 14]]

[[ 3  4]
 [15 16]]

[[ 5  6  7  8  9 10 11]
 [17 18 19 20 21 22 23]]



In [112]:
type(np.hsplit(a,(3,4)))

list

In [113]:
# 可以利用这种特性按一列进行分割
np.hsplit(a,(3,4))

[array([[ 0,  1,  2],
        [12, 13, 14]]), array([[ 3],
        [15]]), array([[ 4,  5,  6,  7,  8,  9, 10, 11],
        [16, 17, 18, 19, 20, 21, 22, 23]])]

In [114]:
for m in np.hsplit(a, (3, 4)):
    print(m)
    print()

[[ 0  1  2]
 [12 13 14]]

[[ 3]
 [15]]

[[ 4  5  6  7  8  9 10 11]
 [16 17 18 19 20 21 22 23]]



## 拷贝
### 没有拷贝

In [115]:
# no copy
a = np.arange(12)
b = a
b is a

True

In [116]:
b.shape = 3, 4
a.shape

(3, 4)

### Shallow Copy 浅拷贝
这是Python的语言特性的概念。
[拷贝](https://docs.python.org/release/3.6.8/library/copy.html)

**切片操作返回的是一个浅拷贝**

In [117]:
# view方法创建一个新的array，其包含了相同的数据
c = a.view()

In [118]:
c is a

False

In [119]:
c.base is a

True

In [120]:
c.shape = 2, 6
a.shape

(3, 4)

In [121]:
c[0, 4] = 1234
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [122]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

因为是一个浅拷贝，所以当切片s中的元素的值改变后，原来a的值也会被改变。

In [123]:
s = a[:, 1:3]
s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### Deep Copy 深拷贝

In [124]:
d = a.copy()

In [125]:
d is a

False

In [126]:
d.base is a

False

In [127]:
d[0, 0] = 999
d

array([[ 999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [128]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## 广播机制 Broadcasting rules
广播允许一般的函数去处理不精准的shape的array。拓展较小的array

In [129]:
a = np.arange(0, 3)
a

array([0, 1, 2])

In [130]:
a * 3

array([0, 3, 6])

上面的代码中3就被拓展为[3, 3, 3]实际执行的是以下的代码

In [131]:
a * [3, 3, 3]

array([0, 3, 6])

## 索引技巧

In [132]:
a = np.arange(10)
a = a * 10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
# 要取出元素的序号
i = np.array([1, 1, 2, 3, 5, 7])
a[i]

array([10, 10, 20, 30, 50, 70])

In [134]:
# 多维序号也支持
j = np.array([[3, 4],
              [5, 6]])
a[j]

array([[30, 40],
       [50, 60]])

In [135]:
# 以下代码是建立一个3维矩阵，示例是通过调色板建立一个图像
palette = np.array([[0,0,0],         # black
                    [255,0,0],       # red
                    [0,255,0],       # green
                    [0,0,255],       # blue
                    [255,255,255]])  # white
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [136]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])
# 选择（0， 2），（1， 1），（1，3），（2，3）
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [138]:
# 选择(0, 2), (1, 2), (1, 2), (2, 2)
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [139]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [140]:
k = (i, j)
a[k]

array([[ 2,  5],
       [ 7, 11]])

**取每一列的最大值的索引序号**

In [141]:
time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20).reshape(5, 4))
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [142]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [143]:
# 每一列的最大值的序号
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1])

In [144]:
print(data[2, 0], data[0, 1], data[3, 2], data[1, 3])

0.9893582466233818 0.8414709848078965 0.9906073556948704 0.6569865987187891


In [145]:
time[ind]

array([ 82.5 ,  20.  , 113.75,  51.25])

In [146]:
data_max = data[ind, range(data.shape[1])]
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [147]:
np.all(data_max == data.max(axis=0))

True

局部操作

In [148]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [149]:
a[[0, 1, 3]] = 0
a

array([0, 0, 2, 0, 4])

In [150]:
a[[2, 3]] = [6, 7]
a

array([0, 0, 6, 7, 4])

In [151]:
a[[0, 1]] += 1
a

array([1, 1, 6, 7, 4])

当索引重复时，会有一些问题

In [152]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

索引重复时，最后一个值操作， 所以第0个元素被赋值为2

In [153]:
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

这里第0个元素为1的原因是，实际上执行的操作是a += 1，最后一个值操作，所以只加了一次

In [154]:
a = np.arange(5)
a[[0,0,2]] += 1
a

array([1, 1, 3, 3, 4])

### 使用Boolean索引

In [155]:
a = np.arange(12).reshape(3, 4)
a > 4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [156]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [158]:
a[a > 4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [159]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [160]:
a = np.arange(12).reshape(3,4)
print(a)
b1 = np.array([False, True, True])
b2 = np.array([True, False, True, False]) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [161]:
a[b1, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
a[:, b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [164]:
a[b1, b2]

array([ 4, 10])

### ix_()函数

In [165]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])
ax, bx, cx = np.ix_(a, b, c)

In [166]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [167]:
bx

array([[[8],
        [5],
        [4]]])

In [168]:
cx

array([[[5, 4, 6, 8, 3]]])

In [169]:
ax.shape

(4, 1, 1)

In [170]:
bx.shape

(1, 3, 1)

In [171]:
cx.shape

(1, 1, 5)

In [172]:
result = ax + bx*cx
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

## 线性代数

In [173]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [174]:
# 转置
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [175]:
a.T

array([[1., 3.],
       [2., 4.]])

In [176]:
# 矩阵的逆 inverse
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [177]:
# eye 代表的意思就是”I“
eye = np.eye(2)
np.linalg.inv(eye)

array([[1., 0.],
       [0., 1.]])

In [178]:
# 对角线元素之和
np.trace(j)

5

## 技巧和提示
1. 用-1去占位不知道的纬度，numpy会自动计算

In [179]:
a = np.arange(30)
a.shape = 2, -1, 3
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

2. 用纬度相同行向量构建一个2维矩阵

In [180]:
x = np.arange(0, 10, 2)
y = np.arange(5)
print(x)
print(y)

[0 2 4 6 8]
[0 1 2 3 4]


In [181]:
m = np.vstack([x, y])
m

array([[0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4]])

In [182]:
m.T

array([[0, 0],
       [2, 1],
       [4, 2],
       [6, 3],
       [8, 4]])

In [183]:
xy = np.hstack([x, y])
xy

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

In [184]:
# 对x, y进行转置也不能构建一个列向量
x = x.T
y = y.T
x

array([0, 2, 4, 6, 8])

In [185]:
y

array([0, 1, 2, 3, 4])

In [186]:
xy = np.hstack([x, y])
xy

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])